from .uninformed import SearchResult, solve_bfs, solve_dfs, solve_dls, solve_iddfs
from .informed import (
    solve_astar_h1,
    solve_astar_h2,
    solve_astar_h1_player,
    solve_astar_h2_player,
    solve_greedy_h1,
    solve_greedy_h2,
    solve_greedy_h1_player,
    solve_greedy_h2_player,
    solve_astar_h2_deadlock,
    solve_astar_h2_player_deadlock,
    solve_greedy_h2_deadlock,
    solve_greedy_h2_player_deadlock,
)

__all__ = [
    "SearchResult",
    "solve_bfs",
    "solve_dfs",
    "solve_dls",
    "solve_iddfs",
    "solve_astar_h1",
    "solve_astar_h2",
    "solve_astar_h1_player",
    "solve_astar_h2_player",
    "solve_greedy_h1",
    "solve_greedy_h2",
    "solve_greedy_h1_player",
    "solve_greedy_h2_player",
    "solve_astar_h2_deadlock",
    "solve_astar_h2_player_deadlock",
    "solve_greedy_h2_deadlock",
    "solve_greedy_h2_player_deadlock",
]
